# Site settings
title: olsen.works
email: scg.olsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Scott Olsen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://olsen.works" # the base hostname & protocol for your site
location: Philadelphia

# Build settings
markdown: kramdown
